### ISSUE TITLE
Add verified Twitch/Twitter/Vimeo tipping to test sheet

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#114]
Add tests for tipping verified twitch/twitter/vimeo creators to test sheet for laptop

**Comment by LaurenWags** [comment]
GitHub and Reddit too.

**Comment by srirambv** [comment]
How about removing rewards from current regression list and have a seperate test run only for rewards? Its basically half the checks now and adding more would make more sense to have a separate test run for rewards done 

@kjozwiak  thoughts?
