### ISSUE TITLE
Test change to brave.com regarding missing media links

### ISSUE THREAD

**Issue by bkero** [brave/qa-resources#124]
In an attempt to address this [issue](https://github.com/brave/brave-com-resources/issues/38) regarding missing links, I've made a [change](https://github.com/brave/devops/pull/1266) to staging.brave.com. 

I'd like some QA assistance to ensure there were no regressions introduced from this change before I deploy this to brave.com.

*tl;dr*: During the transition from static-website-server to WP-Engine (vanilla Wordpress), some media links stopped working.

Wordpress Attachment Pages are not served from `/$POSTNAME/$FILENAME`, but are actually served from `/wp-content/uploads/$YYYY/$MM/$FILENAME`.

To fix this I've done 3 things:

* Constructed redirects (specifically for PDF files): in the PR adding these 2 lines:

```
if (req.url ~ "^\/.*\/([A-Za-z0-9-_]+\.pdf)$") { set req.url = "/wp-content/uploads/" re.group.match.1; } # matches /abc/def.pdf
if (req.url ~ "^\/([A-Za-z0-9-_]+\.pdf)$") { set req.url = "/wp-content/uploads" re.group.match.0; } # matches /abc.pdf
``` 

* Turned off the Wordpress option `Organize my uploads into month- and year-based folders`
* Copied all `/wp-content/uploads/$YYYY/$MM/*.*` to `/wp-content/uploads/`

**Comment by LaurenWags** [comment]
- Verified https://brave.com/update-on-gdpr-complaint-rtb-ad-auctions/4-appendix-on-market-saturation-of-the-systems.pdf loads the PDF correctly.

- Verified the following PDF documents loaded correctly on https://brave.com/dpc-google/
   * https://brave.com/Behavioural-advertising-and-personal-data.pdf 
   * https://brave.com/update-rtb-ad-auction-gdpr/Google-publisher-verticals-marked-up.pdf

- Verified the following PDF documents loaded correctly on https://brave.com/update-on-gdpr-complaint-rtb-ad-auctions/
   * https://brave.com/Panoptykon_UODO_skarga-na-Google_28.01.2019_final.pdf
   * https://brave.com/Panoptykon_UODO_skarga-na-IAB_28.01.2019_final.pdf

-

**Comment by srirambv** [comment]
* Verified embedded media plays correctly 
* Verified embedded images are loaded correctly and hyperlinked images are loaded correctly 
* Verified all linked PDF documents on the following pages are loaded correctly
  - https://brave.com/ico-adtech-update-rtb/ 
  - https://brave.com/update-rtb-ad-auction-gdpr/ 
  - https://brave.com/adtech-data-breach-complaint/
  - https://brave.com/update-on-gdpr-complaint-rtb-ad-auctions/
  - https://brave.com/adtech-data-breach-complaint/
  - https://brave.com/iab-cookie-wall/
  - https://brave.com/european-commission-sector-inquiry/

* Some URL's mentioned in references/footnotes are not hyperlinked while others on the same page are. The following sections on each page have missing hyperlinks
  - Section: https://brave.com/senate-qrfs-june2019/#_ftnref5 
  - Section: https://brave.com/senate-qrfs-june2019/#_ftnref12
  - Section: https://brave.com/senate-qrfs-june2019/#_ftnref13
  - Section: https://brave.com/senate-qrfs-june2019/#_ftnref15
  - Section: https://brave.com/senate-qrfs-june2019/#_ednref1 
all on  https://brave.com/senate-qrfs-june2019/
  - Section: https://brave.com/european-commission-sector-inquiry/#_ftnref3 on https://brave.com/european-commission-sector-inquiry/
  - Section: https://brave.com/dpc-google/#_ednref2 on https://brave.com/dpc-google/
  - Section: https://brave.com/dcn-letter-rtb/#_ftnref3 on https://brave.com/dcn-letter-rtb/
  - 

Incorrect hyperlinking in footnote section on  https://brave.com/senate-qrfs-june2019/. URL is hyperlinked leaving `https://` and the full URL text
![image](https://user-images.githubusercontent.com/17010094/60513538-8071f680-9ca5-11e9-9f56-a582d3db4ffe.png)

Not sure if these two should have some hyperlinks to them to associate the documents on https://brave.com/update-on-gdpr-complaint-rtb-ad-auctions/
![image](https://user-images.githubusercontent.com/17010094/60513904-4f45f600-9ca6-11e9-9b9d-f8dedb401633.png)


cc: @johnnyryan @bkero @w0ts0n

**Comment by srirambv** [comment]
@bkero closing the issue as QA verification for the missing media is done. The second part of clean up can be checked once its done. Closing the issue for now. Please reopen if you thing otherwise
