### ISSUE TITLE
Test basicattention.org WP-Engine migration for breakage

### ISSUE THREAD

**Issue by bkero** [brave/qa-resources#129]
As explained in the https://github.com/brave/devops/issues/1350 we're migrating basicattentiontoken.org to WP-Engine. We'd like some QA assistance ensuring there were no regressions caused by the migration.

The dev site is up at https://batdotorgdev.wpengine.com/

On Friday I'll be taking a fresh clone of basicattentiontoken.org and moving it to staging.basicattentiontoken.org with Fastly acting as a CDN.

**Comment by bkero** [comment]
This just hit staging A few known issues:

The link format in the Terms of Service is wrong in the footer. This is a Divi issue (or plugin interaction). There are also some broken images due to wrong image link located on the page https://staging.basicattentiontoken.org/into-the-blockchain-brave-with-metamask/

**Comment by LaurenWags** [comment]
Additional notes
- images missing as per https://github.com/brave/qa-resources/issues/129#issuecomment-508852914
- video missing from main page
- @bkero does the link format issue you mentioned in https://github.com/brave/qa-resources/issues/129#issuecomment-508852914 also cover the Privacy Policy link in the footer? that doesn't seem to be going to the correct place on staging site when compared with prod site.
- when on a specific blog post or just https://staging.basicattentiontoken.org/blog/, if you click on the author, the URL you are taken to has `/author/` in the middle of the resulting URL. Production doesn't have this. Both seem to work, not sure if this is a problem or not.

**Comment by bkero** [comment]
The link format issue is the same for Privacy Policy as the Terms of Service links. It appears to be a problem with Divi altering links. Unsure why we did not encounter this problem on brave.com. I am working with @rossmoody on fixing this.

I cannot replicate the video missing from the main page. Can you try to get some more information on this to me so I can replicate?

The author URL behavior is likely a modification to the structure of  the URLs from the static-site-webserver. Wordpress puts author pages at `/author/`. If we want to replicate this behavior we will have to use this plugin. https://www.wpbeginner.com/plugins/how-to-change-author-url-slug-and-base-in-wordpress/

**Comment by w0ts0n** [comment]
Thanks for highlighting. I think the /author/ bug is a non issue. That page doesn't isn't too important for SEO or anything else and I don't think anyone is going to mind the URL change.

**Comment by LaurenWags** [comment]
@bkero re: video - it was missing along with images. somehow throughout browsing, it re-appeared. will see if it happens again.

**Comment by kjozwiak** [comment]
@LaurenWags started going through the website myself, noticed that the video icon was also missing:

<img width="887" alt="Screen Shot 2019-07-12 at 1 47 11 PM" src="https://user-images.githubusercontent.com/2602313/61147949-ad938580-a4ab-11e9-8c8d-e17db6631b4d.png">

Is that the video being referred at https://github.com/brave/qa-resources/issues/129#issuecomment-510969768?

**Comment by LaurenWags** [comment]
yep @kjozwiak ! when I first saw it, the entire box where 'Get Brave' is shown was missing.

**Comment by kjozwiak** [comment]
@LaurenWags found the reason why images/videos aren't loading initially. They're being loaded from https://batdotorgstg.wpengine.com. You'll need to authenticate with both https://staging.basicattentiontoken.org and https://batdotorgstg.wpengine.com. Once you've authenticated with both, the page should start loading images/videos etc... Example:

<img width="1099" alt="Screen Shot 2019-07-12 at 2 20 40 PM" src="https://user-images.githubusercontent.com/2602313/61149938-43c9aa80-a4b0-11e9-8a7d-5f0eec1e11a9.png">

@w0ts0n @bkero is the above expected in terms of images and other resources being loaded from https://batdotorgstg.wpengine.com instead of https://staging.basicattentiontoken.org?

**Comment by kjozwiak** [comment]
Also noticed that under https://staging.basicattentiontoken.org, clicking on `中文` loads the correct version of the translated website, however it also includes the navigation bar at the top of the page and https://basicattentiontoken.org/index_1/ doesn't. Example:

**https://staging.basicattentiontoken.org example:**

<img width="1358" alt="Screen Shot 2019-07-12 at 3 05 54 PM" src="https://user-images.githubusercontent.com/2602313/61152599-e5ec9100-a4b6-11e9-8566-8121f3b6984d.png">

**https://basicattentiontoken.org/index_1/ example:**

![Screen Shot 2019-07-12 at 3 06 11 PM](https://user-images.githubusercontent.com/2602313/61152624-f43aad00-a4b6-11e9-949d-bdc252c73353.png)

**Comment by kjozwiak** [comment]
Noticed that the heads are missing from blog posts under https://staging.basicattentiontoken.org. Example using https://staging.basicattentiontoken.org/guest-ama-with-mycrypto/:

**https://staging.basicattentiontoken.org example:**

<img width="1400" alt="Screen Shot 2019-07-12 at 3 21 57 PM" src="https://user-images.githubusercontent.com/2602313/61154328-d28ff480-a4bb-11e9-8eaf-78c5c2a4e1b7.png">

**https://basicattentiontoken.org/ example:**

![Screen Shot 2019-07-12 at 3 22 05 PM](https://user-images.githubusercontent.com/2602313/61154342-e0457a00-a4bb-11e9-80d5-7d7e687af2cf.png)

**Comment by kjozwiak** [comment]
Seeing the following under https://staging.basicattentiontoken.org/blog/ as well:

<img width="859" alt="Screen Shot 2019-07-12 at 3 45 05 PM" src="https://user-images.githubusercontent.com/2602313/61154541-5f3ab280-a4bc-11e9-9ecc-b68f601c15b5.png">

**Comment by kjozwiak** [comment]
@w0ts0n @bkero as much as I could with site and it generally looks like it's working 👍 Here's the possible issues that I've noticed:

* https://github.com/brave/qa-resources/issues/129#issuecomment-510985348
* https://github.com/brave/qa-resources/issues/129#issuecomment-511000212
* https://github.com/brave/qa-resources/issues/129#issuecomment-511010395
* https://github.com/brave/qa-resources/issues/129#issuecomment-511011402
* Under the footer, `Users` pointing to https://staging.basicattentiontoken.org/?page_id=3140
* Under the footer, `Creators` pointing to https://staging.basicattentiontoken.org/?page_id=3071
* Under the footer, `Advertisers` pointing to https://staging.basicattentiontoken.org/?page_id=7964

**Comment by rossmoody** [comment]
I tried quite a few things to fix the footer links to no avail. They're going to the right pages so I don't know if it's worth blocking on but I spent quite a bit of time on it.

**Comment by bkero** [comment]
@kjozwiak I've just done a search-replace to remove the old links. That should fix the batdotorgstg links.

As to the footer links, @rossmoody can replicate the problem I have fixing these, and we are considering escalating this issue to Divi.

**Comment by rossmoody** [comment]
> Seeing the following under https://staging.basicattentiontoken.org/blog/ as well:
> 
> <img alt="Screen Shot 2019-07-12 at 3 45 05 PM" width="859" src="https://user-images.githubusercontent.com/2602313/61154541-5f3ab280-a4bc-11e9-9ecc-b68f601c15b5.png">

fixed

**Comment by bkero** [comment]
I've migrated basicattentiontoken.org over to this new system as well, making sure to check that each of these problems was addressed. Please confirm.

**Comment by bkero** [comment]
Going to call this done.
