### ISSUE TITLE
Test new https everywhere endpoint

### ISSUE THREAD

**Issue by bkero** [brave/qa-resources#147]
We recently set up a Fastly CDN fronted proxy to a S3 bucket that hosts data files for HTTPS-Everywhere.

We need QA to test this out and make sure its working correctly. The address is https://https-everywhere.s3.brave.com/ . Paths should be the same. I believe a custom-built browser will be necessary for this.

**Comment by w0ts0n** [comment]
This isn't needed anymore.

**Comment by bkero** [comment]
Going to re-open this (hopefully). This turns out to be needed since we found out that the Android client actually uses these resources.

**Comment by bkero** [comment]
Opened at https://github.com/brave/qa-resources/issues/150
