### ISSUE TITLE
Update Windows test sheet to add x86 Update test

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#148]
Windows test run should be updated to include an x86 upgrade check

**Comment by srirambv** [comment]
Are we going to start testing x86 again?

**Comment by LaurenWags** [comment]
no, this is just to verify that updates work on x86. @kjozwiak does it on the side and I didn't know - we should add it into our regular process so it doesn't get missed/forgotten about.

**Comment by kjozwiak** [comment]
@srirambv as @LaurenWags mentioned, it's only during releases. I always check to make sure the following on x86:

* ensure that installing the new version on x86 works without any issues
* updated on x86 works without any issues (usually via the test channel stubs)

**Comment by LaurenWags** [comment]
Might not make sense to add this any more since Win 7 and 8.1 are no longer supported and Win 11 doesn't have x86 (afaik).

Since this is explicitly part of the release checklist, going to close this off as stale.
