### ISSUE TITLE
Rewards overhaul - desktop

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#151]
Rewards/Ads section of desktop test run needs a complete overhaul.

While doing this, should include a check for confirming that AC does not go thru if AC and/or Rewards is toggled off.

**Comment by srirambv** [comment]
Should be done for mobile as well

**Comment by LaurenWags** [comment]
would need your input on mobile @srirambv since it does not have parity with desktop 👍

**Comment by srirambv** [comment]
Sure. I can help with the Mobile specific checks.

**Comment by srirambv** [comment]
Adding internal discussion thread for easier access https://bravesoftware.slack.com/archives/GAA4017R7/p1576267967026700
