### ISSUE TITLE
Testing for Static Version of Home Page

### ISSUE THREAD

**Issue by AlanBreck** [brave/qa-resources#177]
We are in the process of migrating core pages of brave.com from WordPress to a static website. Given the high priority of the home page, I'd like to request Q/A on the page.

**Test URL:** https://staging.brave.com/ (basic auth credentials found in Websites vault in 1Password)
**Baseline URL:** https://brave.com/

Please let me know if you need me to put together more formal test cases (guidance on this appreciated), however here are a few areas that would need testing:

- The "Download Brave for ..." should display the appropriate platform for the current device (iOS, Android, Linux, etc)
- The referral code should be appended to the download link if present (NOTE: ref code not appended to direct platform downloads):
  - Step 1: visit https://staging.brave.com/w0ts0n
  - Step 3: ensure `WTS071` is appended to download url.
- All download links should work
- Animations should be playing in all platforms/browsers
- While there are some slight cosmetic differences between the pages, there should be parity between the original and the static page in cosmetics and functionality
- Images should work in all platforms/browsers
- FAQ accordion should function properly in all platforms/browsers

NOTE: this page will ultimately be translated into Japanese, Chinese, Korean, Chinese (simplified), French, and German. While I don't expect there to be significant differences from a Q/A perspective, please comment below if you'd prefer to wait and be notified when the remaining translations are complete.

**[UPDATE - translations complete]**
Translations for French, Japanese, and Korean are complete:
- French: https://staging.brave.com/fr
- Japanese: https://staging.brave.com/ja
- Korean: https://staging.brave.com/ko
- German: https://staging.brave.com/de
- Chinese (simplified): https://staging.brave.com/zh

Remaining translations:
- [x] Chinese (simplified)
- [x] German

**Comment by kjozwiak** [comment]
Verified test plan from https://github.com/brave/qa-resources/issues/171#issue-658601642 for the below OSes/Browsers/Locales:

<details>
<summary>Case 1 - **PASSED** using macOS 10.15.6 x64 Catalina - EN</summary>

Browser being used: `MS Edge - 85.0.564.44 (Official build) Beta (64-bit)`

**`Downloads/Referrals`**
 
* Confirmed clicking on the download button correctly downloaded the `DMG` executable as per the following:
  * https://laptop-updates.brave.com/latest/osx - https://brave-browser-downloads.s3.brave.com/latest/Brave-Browser.dmg
*  Confirmed clicking on that download button correctly downloaded the `PKG` executable with `WTS071` appended after visiting https://staging.brave.com/w0ts0n which redirected to https://staging.brave.com/?ref=WTS071/ as per the following:
  * https://laptop-updates-staging.brave.com/download/WTS071 - https://referrals.brave.com/latest/Brave-Browser-WTS071.pkg
* Confirmed that direct platform download links (below the main download button) doesn't have referral code appended to the download URL once visiting https://staging.brave.com/w0ts0n which redirects to https://staging.brave.com/?ref=WTS071/
  * https://laptop-updates-staging.brave.com/latest/winx64 - https://referrals.brave.com/latest/BraveBrowserSetup.exe
  * https://laptop-updates-staging.brave.com/latest/winia32 - https://referrals.brave.com/latest/BraveBrowserSetup32.exe
  * https://laptop-updates-staging.brave.com/latest/osx - https://referrals.brave.com/latest/Brave-Browser.pkg
  * https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
* Confirmed that mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
  * Clicking on GPS --> https://play.google.com/store/apps/details?id=com.brave.browser&hl=en
  * Clicking on iOS App Store --> https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?mt=8&ign-mpt=uo%3D4

 **`UX/UI`**

* ensured that https://staging.brave.com looks correct and matches https://brave.com when using `EN`
* ensured that the "Download Brave for..." Button displayed `macOS`
  * https://laptop-updates.brave.com/latest/osx - https://brave-browser-downloads.s3.brave.com/latest/Brave-Browser.dmg
* ensured that scrolling through https://staging.brave.com didn't cause any performance issues or noticeable jank
* ensured that the animations are working as expected when scrolling through https://staging.brave.com
* ensured that the `Browser`, `Content Creators`, `Advertisers`, `Company` and `Blog` menus worked as expected
* ensured that the following links on https://staging.brave.com opened the correct pages
  * `Learn more about Brave Shields` - https://support.brave.com/hc/en-us/articles/360022973471-What-is-Shields-
  * `Get the browser now` - https://staging.brave.com/download/
  * `Learn more about Private Browsing` - https://support.brave.com/hc/en-us/articles/360018121491-What-is-a-Private-Window-with-Tor-
  * `Learn more about Brave Rewards (under the BRAVE REWARDS heading)` - https://staging.brave.com/brave-rewards/
  * `Learn more about Brave Rewards (under the A BETTER DEAL heading)` - https://staging.brave.com/brave-rewards/
* ensured that the FAQ at the bottom of https://staging.brave.com correctly expands/collapses
  * `Why is my privacy so important?` - ensured link points to https://www.wired.com/2006/05/the-eternal-value-of-privacy/ - **PASSED**
  * `Is Brave free?` - ensured link points to https://brave.com/features/ **PASSED**
  * `How do I get paid for viewing ads if Brave blocks ads?` - ensured link points to https://brave.com/brave-rewards/ - **PASSED**
  * `How much can you earn from viewing Brave Ads?` - **PASSED**
  * `Can I install extensions in Brave?` - ensured link points to https://chrome.google.com/webstore/category/extensions - **PASSED**

<img width="1629" alt="Screen Shot 2020-09-08 at 3 22 56 PM" src="https://user-images.githubusercontent.com/2602313/92519843-a7e91b00-f1e8-11ea-85f0-18d0f07c215d.png">

</details>

**Comment by LaurenWags** [comment]
Verified test plan from https://github.com/brave/qa-resources/issues/177#issue-686693792 for the below OSes/Browsers/Languages:

<details>
<summary>1. macOS Mojave 10.14.6 - `en`</summary>

- Used Safari `13.0.5` as the browser to check the below items on staging.brave.com
- Confirmed "Download Brave for..." buttons used correct OS

<img width="1278" alt="macOS-en-1" src="https://user-images.githubusercontent.com/28145373/92524000-6019c200-f1ef-11ea-9a2b-2286cab70ff8.png">
<img width="1275" alt="macOS-en-2" src="https://user-images.githubusercontent.com/28145373/92524002-614aef00-f1ef-11ea-9b88-89543fc74e7b.png">

- Confirmed all download buttons on the page worked as expected without ref code (.dmg was downloaded on macOS)
- Confirmed platform specific links downloaded the expected file (BraveBrowserSetup.exe for Windows x64, BraveBrowserSetup32.exe for Windows x86, directed to readthedocs for Linux)
- Visited staging.brave.com/w0ts0n and confirmed I was redirected to `https://staging.brave.com/?ref=WTS071/`
- Confirmed `WTS071` was appended to download URL when hovering over download buttons
- Confirmed Brave-Browser-WTS071.pkg was downloaded
- Confirmed all download buttons on the page worked as expected with ref code (.pkg with ref code was downloaded on macOS as in above step)
- Confirmed platform specific links do not append ref code (Hovered over link, confirmed no ref code in URL. Clicked on link, confirmed no ref code appended to file name when downloading.)
- Confirmed all expected animations worked (matched brave.com)
- Generally confirmed staging.brave.com generally looked like brave.com (minor cosmetic differences in fonts/spacing were reported to @AlanBreck)
- Confirmed no broken images on the page
- Confirmed FAQ accordion (at the bottom of the page) worked as expected - expanded/collapsed each item
- Spot checked additional content/links throughout the page

</details>

**Comment by AlanBreck** [comment]
This looks like a go. Thank you so much to both of you, @kjozwiak and @LaurenWags!

**Comment by LaurenWags** [comment]
@AlanBreck we've still got some Win x86 and mobile checks to do first 😄

**Comment by AlanBreck** [comment]
Aha! I guess I was being a bit excitable. I'll patiently await. ;-)

**Comment by kjozwiak** [comment]
QA has completed verifications as per https://github.com/brave/qa-resources/issues/177#issuecomment-689090514 and https://github.com/brave/qa-resources/issues/177#issuecomment-689114835.
