### ISSUE TITLE
Update Android test run generator

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#18]
Update Data section of Android test run generator:

## Data 
Pre-Requisite: Put previous build shortcut on home screen. Also have several sites 'Added to home screen' (from 3 dots menu). Then update previous build to test build.
- [ ] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [ ] Verify that the cookies from the previous build are preserved in the updated build
- [ ] Verify shortcut is still available on home screen after updating Brave
- [ ] Verify sites added to home screen are still visible and able to be used after updating Brave.

**Comment by srirambv** [comment]
Merged to master. Closing issye
