### ISSUE TITLE
Testing https://brave5t5rjjg3s6k.onion

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#189]
We've recently setup a Brave `.onion` address via https://brave5t5rjjg3s6k.onion. We should run through a quick regression check on a few platforms just to make sure things are working as expected. Some key points:

* ensure that browsing through the website keeps you within the `.onion` domain
* ensure that downloads are going through the Tor proxy as well

CCing @w0ts0n @bkero

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.6 x64 (Catalina)` using the following build:

```
Brave | 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
-- | --
Revision | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS | macOS Version 10.15.6 (Build 19G73)
```

### General Cases

* ensured that https://brave5t5rjjg3s6k.onion loads/resolves using a Tor Windows/Tabs using Brave
  * ensured that https://brave5t5rjjg3s6k.onion doesn't resolve on Normal/Guest Windows/Tabs
* ensured that https://brave5t5rjjg3s6k.onion loads/resolves using the Tor Browser
* ensured that traffic from Tor isn't being logged via Little Snitch/Charles Proxy

### Dropdown Navigation

Running through the dropdown items and ensuring that all the links are being routed through `.onion` as per the following:

* **`Browser`**
  * https://brave5t5rjjg3s6k.onion/features/
  * https://brave5t5rjjg3s6k.onion/brave-rewards/
  * https://brave5t5rjjg3s6k.onion/tips/
* **`Content Creators`**
  * https://creators.brave5t5rjjg3s6k.onion/
  * https://brave5t5rjjg3s6k.onion/media-assets/
* **`Advertisers`**
  * https://brave5t5rjjg3s6k.onion/brave-ads/
* **`Company`**
  * https://brave5t5rjjg3s6k.onion/about/
  * https://brave5t5rjjg3s6k.onion/careers/
  * https://community.brave5t5rjjg3s6k.onion/
  * https://brave5t5rjjg3s6k.onion/brave-branding-assets/
* **`Blog`**
  * https://brave5t5rjjg3s6k.onion/blog/
  * https://brave5t5rjjg3s6k.onion/insights/
  * https://brave5t5rjjg3s6k.onion/research/

### Downloads

Running through `downloads` via https://brave5t5rjjg3s6k.onion

* Clicking on `Download Brave on macOS` (main button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/osx
     * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser.pkg
* Clicking on `Windows 64-bit` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/winx64
    * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/BraveBrowserSetup.exe
* Clicking on `Windows 32-bit` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/winia32
   * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/BraveBrowserSetup32.exe
* Clicking on `macOS` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/osx
    * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser.pkg

Running through `downloads` via https://brave5t5rjjg3s6k.onion/download/

* Clicking on `Download Brave on macOS` (main button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/osx
     * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser.pkg
* Clicking on `Windows 64-bit` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/winx64
    * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/BraveBrowserSetup.exe
* Clicking on `Windows 32-bit` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/winia32
   * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/BraveBrowserSetup32.exe
* Clicking on `macOS` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/osx
    * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser.pkg

Checked and ensured that referral codes were also working via `.onion` as per the following:

* Visited https://brave5t5rjjg3s6k.onion/red194 and ensured I was redirected to https://brave5t5rjjg3s6k.onion/?ref=red194
* Clicking on `Download Brave on macOS` (main button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/download/RED194
     * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser-RED194.pkg

https://brave5t5rjjg3s6k.onion/download/

* Visited https://brave5t5rjjg3s6k.onion/red194 and ensured I was redirected to https://brave5t5rjjg3s6k.onion/?ref=red194
* Clicking on `Download Brave on macOS` (main button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/download/RED194
     * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser-RED194.pkg

**Comment by kjozwiak** [comment]
Possible issues:

Seems like https://support.brave5t5rjjg3s6k.onion/hc/en-us doesn't load correctly in Brave's Tor Windows/Tabs. However, it loads fine in the Tor browser. Examples:

| Brave Tor Window/Tab | Brave Regular Window/Tab | Tor Browser |
| ------------- | ------------- | ------------- |
| <img width="1141" alt="Screen Shot 2020-09-28 at 6 11 54 PM" src="https://user-images.githubusercontent.com/2602313/94492764-0175b180-01b9-11eb-974c-b260527c7b22.png">  | <img width="1134" alt="Screen Shot 2020-09-28 at 6 33 26 PM" src="https://user-images.githubusercontent.com/2602313/94492815-1f431680-01b9-11eb-82bc-2c5e8fe1d2d5.png">  | <img width="1018" alt="Screen Shot 2020-09-28 at 6 34 14 PM" src="https://user-images.githubusercontent.com/2602313/94492854-397cf480-01b9-11eb-8de4-05a6f486f98d.png"> |

**Comment by LaurenWags** [comment]
Verification on `macOS 10.14.6 (Mojave)` using the below version of Tor Browser:

```
10.0 (based on Mozilla Firefox 78.3.0esr) (64-bit)
```

* ensured that https://brave5t5rjjg3s6k.onion loads/resolves using the Tor Browser

### Dropdown Navigation

Running through the dropdown items and ensuring that all the links are being routed through `.onion` as per the following:

* **`Browser`**
  * https://brave5t5rjjg3s6k.onion/features/
  * https://brave5t5rjjg3s6k.onion/brave-rewards/
  * https://brave5t5rjjg3s6k.onion/tips/
* **`Content Creators`**
  * https://creators.brave5t5rjjg3s6k.onion/
* **`Advertisers`**
  * https://brave5t5rjjg3s6k.onion/brave-ads/
* **`Company`**
  * https://brave5t5rjjg3s6k.onion/about/
  * https://community.brave5t5rjjg3s6k.onion/
* **`Blog`**
  * https://brave5t5rjjg3s6k.onion/blog/

### Downloads

Running through `downloads` via https://brave5t5rjjg3s6k.onion

* Clicking on `Download Brave on macOS` (main button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/osx
     * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser.pkg
     * Installed and launched this version
     * Confirmed it was the latest (`1.14.84`) release version
* Clicking on `Windows 64-bit` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/winx64
    * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/BraveBrowserSetup.exe
* Clicking on `Windows 32-bit` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/winia32
   * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/BraveBrowserSetup32.exe
* Clicking on `macOS` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/osx
    * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser.pkg
* Clicking on `Linux` (underneath the main download button)
   * was navigated to https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

Running through `downloads` via https://brave5t5rjjg3s6k.onion/download/

* Clicking on `Download Brave on macOS` (main button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/osx
     * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser.pkg
     * Installed and launched this version
     * Confirmed it was the latest (`1.14.84`) release version
* Clicking on `Windows 64-bit` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/winx64
    * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/BraveBrowserSetup.exe
* Clicking on `Windows 32-bit` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/winia32
   * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/BraveBrowserSetup32.exe
* Clicking on `macOS` (underneath main download button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/latest/osx
    * Downloaded https://referrals.brave5t5rjjg3s6k.onion/latest/Brave-Browser.pkg
* Clicking on `Linux` (underneath the main download button)
   * was navigated to https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

Checked and ensured that referral codes were also working via `.onion` as per the following:

* Visited https://brave5t5rjjg3s6k.onion/kam253 and ensured I was redirected to https://brave5t5rjjg3s6k.onion/?ref=kam253
* Clicking on `Download Brave on macOS` (main button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/download/KAM253
     * **FAIL** Attempts to download `BraveBrowserSetup32-KAM253.exe`
<img width="994" alt="Screen Shot 2020-09-29 at 10 10 07 AM" src="https://user-images.githubusercontent.com/28145373/94569869-3119cd80-023c-11eb-8ff4-f8d1acc03abe.png">


https://brave5t5rjjg3s6k.onion/download/

* Visited https://brave5t5rjjg3s6k.onion/kam253 and ensured I was redirected to https://brave5t5rjjg3s6k.onion/?ref=kam253
* Clicked on Download button in header, was navigated to https://brave5t5rjjg3s6k.onion/download/
* Clicking on `Download Brave on macOS` (main button)
  * https://laptop-updates.brave5t5rjjg3s6k.onion/download/KAM253
     * **FAIL** Attempts to download `BraveBrowserSetup32-KAM253.exe`
<img width="997" alt="Screen Shot 2020-09-29 at 10 12 24 AM" src="https://user-images.githubusercontent.com/28145373/94570008-5a3a5e00-023c-11eb-863c-309445a872af.png">


------------------------

**Comment by LaurenWags** [comment]
Reproduced https://github.com/brave/qa-resources/issues/189#issuecomment-700319198 using 1.15.x Tor Window in Brave. Occurs when shields are up (default values) or down.
<img width="1450" alt="Screen Shot 2020-09-29 at 11 31 11 AM" src="https://user-images.githubusercontent.com/28145373/94579981-60820780-0247-11eb-9b96-e479c5dcb30b.png">

Does not reproduce with Tor browser `10.0`.
<img width="995" alt="Screen Shot 2020-09-29 at 11 31 48 AM" src="https://user-images.githubusercontent.com/28145373/94579992-62e46180-0247-11eb-9789-cf36545ac594.png">

**Comment by kjozwiak** [comment]
Closing 👍 Thanks for the hard work @LaurenWags & @GeetaSarvadnya!
