### ISSUE TITLE
Test new, alternate home page

### ISSUE THREAD

**Issue by AlanBreck** [brave/qa-resources#191]
We’re releasing a new home page design (for English) with alternate messaging when users visit the site using Chrome. The only changes are the “above fold” hero content. Could @quality-team do a pass to ensure that the previous functionality still works (essentially just the download button), but also check that the alternate messaging works for Chrome users? This should not display Chrome text for merely Chromium users (like Opera and Edge), though Vivaldi unavoidably displays Chrome messaging as they explicitly removed any means of distinguishing them from others.

**Test URL:** https://staging.brave.com/ (basic auth credentials found in Websites vault in 1Password)

**New functionality**
- Chrome users (but **not** merely Chromium users) should see alternate text:
![1440x850](https://user-images.githubusercontent.com/1199820/94618413-1d408c80-0279-11eb-9322-162c422d055c.png)

- Non-Chrome users on the English version should see an updated hero section:
![1440x850](https://user-images.githubusercontent.com/1199820/94724743-bb3f6000-0328-11eb-8f03-b4dc02833da7.png)

**Existing functionality which should continue to work**
- The "Download Brave for ..." should display the appropriate platform for the current device (iOS, Android, Linux, etc)
- The referral code should be appended to the download link if present (NOTE: ref code not appended to direct platform downloads):
  - Step 1: visit https://staging.brave.com/w0ts0n
  - Step 3: ensure `WTS071` is appended to download url.
  - All non-English languages should be unaffected by the changes

**Comment by LaurenWags** [comment]
Verification in progress

<details>
<summary>PASSED - macOS 10.14.6 x64 (Mojave)</summary>

* Confirmed new page is displayed when using `Chrome 85.0.4183.121 (Official Build) (64-bit)` in English
   * Confirmed clicking on `Download Brave for macOS` downloaded `Brave-Browser.pkg` as expected.
<img width="1267" alt="macOS-Chrome1" src="https://user-images.githubusercontent.com/28145373/94725721-38b7a000-032a-11eb-9d3d-fa8cd355afec.png">

   * Checked `fr`, `de`, `zh` languages - confirmed existing brave.com page is served to Chrome for these languages
<img width="876" alt="macOS-Chrome2" src="https://user-images.githubusercontent.com/28145373/94725724-3b19fa00-032a-11eb-968f-9ccd104e87c5.png">

* Visited staging.brave.com/w0ts0n to confirm referrals are working on Chrome. Confirmed was redirected to https://staging.brave.com/?ref=WTS071/ as expected.
   * Confirmed clicking on `Download Brave for macOS` on https://staging.brave.com/?ref=WTS071/ downloaded the appropriately tagged `Brave-Browser-WTS071.pkg` file
   * Confirmed that the referral code persists into brave.com/download when navigating from https://staging.brave.com/?ref=WTS071/ on Chrome

* Checked `Safari 13.0.5 (14608.5.12)` and ensured staging.brave.com is different from Chrome image above
<img width="1273" alt="macOS-Safari" src="https://user-images.githubusercontent.com/28145373/94725751-440acb80-032a-11eb-8e2a-c98a05aa5cee.png">

* Checked `Microsoft Edge 85.0.564.63 (Official build) (64-bit)` and ensured staging.brave.com is different from Chrome image above
<img width="1036" alt="macOS-Edge" src="https://user-images.githubusercontent.com/28145373/94725757-466d2580-032a-11eb-822f-0367b07127cd.png">

* Checked `Brave 1.15.61` and ensured staging.brave.com is different from Chrome image above
<img width="1133" alt="macOS-Brave" src="https://user-images.githubusercontent.com/28145373/94725763-49681600-032a-11eb-965e-7395cf3cbabd.png">

* Checked referral using staging.brave.com/w0ts0n on Edge and confirmed `Brave-Browser-WTS071.pkg` was downloaded as expected

</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** via the following cases. Each case outlines the browser build that used during verification 👍 

<details>
<summary>macOS 10.15.6 x64 (Catalina) - PASSED</summary>
<br>

* ensured that the new page is being displayed when using `Chrome 85.0.4183.121 (Official Build) (64-bit)`
   * ensured that clicking on `Download Brave for macOS` downloaded `Brave-Browser.pkg`
     * https://laptop-updates-staging.brave.com/latest/osx - https://referrals.brave.com/latest/Brave-Browser.pkg

<img width="1458" alt="Screen Shot 2020-09-30 at 9 24 16 PM" src="https://user-images.githubusercontent.com/2602313/94755834-d380a080-0363-11eb-90cc-975b9ce576f8.png">

* ensured that brave.com loads the standard page (not targeting Chrome) when visiting using `ko`, `ja` or `fr` locales using `Chrome 85.0.4183.121 (Official Build) (64-bit)`

| `ko` | `ja` | `fr` |
| ----- | --- | ---- |
| <img width="1472" alt="Screen Shot 2020-09-30 at 9 33 17 PM" src="https://user-images.githubusercontent.com/2602313/94756173-b8faf700-0364-11eb-97db-f0e23ff426d5.png"> | <img width="1554" alt="Screen Shot 2020-09-30 at 9 33 39 PM" src="https://user-images.githubusercontent.com/2602313/94756187-c3b58c00-0364-11eb-8d95-80d2a0b5b871.png">| <img width="1562" alt="Screen Shot 2020-09-30 at 9 33 54 PM" src="https://user-images.githubusercontent.com/2602313/94756201-ce702100-0364-11eb-94c9-13b8347a2774.png"> |

* visited `staging.brave.com/w0ts0n` and confirmed that referrals are working using `Chrome 85.0.4183.121 (Official Build) (64-bit)`
  * ensured `staging.brave.com/w0ts0n` redirects to `https://staging.brave.com/?ref=WTS071/`
  * ensured that clicking on `Download Brave for macOS` on `https://staging.brave.com/?ref=WTS071/` downloaded the appropriately tagged `Brave-Browser-WTS071.pkg` file.
     * https://laptop-updates-staging.brave.com/download/WTS071 - https://referrals.brave.com/latest/Brave-Browser-WTS071.pkg
   * ensured that the referral code persists via the following:
     * `https://staging.brave.com/`
     * `https://staging.brave.com/download/`

| `FX 81.0 (64-bit)` | `Opera GX LVL 2 (core: 71.0.3770.205` | `Edge 86.0.622.28 (Official build) Beta (64-bit)` |
| ----- | --- | ---- |
| <img width="1304" alt="Screen Shot 2020-09-30 at 10 54 28 PM" src="https://user-images.githubusercontent.com/2602313/94760232-ea2cf480-036f-11eb-8279-1e9071ef6ef6.png"> | <img width="1461" alt="Screen Shot 2020-09-30 at 10 50 52 PM" src="https://user-images.githubusercontent.com/2602313/94760083-93271f80-036f-11eb-8dd1-329381957dc8.png"> | <img width="1611" alt="Screen Shot 2020-09-30 at 10 53 37 PM" src="https://user-images.githubusercontent.com/2602313/94760167-cc5f8f80-036f-11eb-9199-03250c220169.png"> |

* visited `staging.brave.com/w0ts0n` and confirmed that referrals are working using `Opera GX LVL 2 (core: 71.0.3770.205`
  * ensured `staging.brave.com/w0ts0n` redirects to `https://staging.brave.com/?ref=WTS071/`
  * ensured that clicking on `Download Brave for macOS` on `https://staging.brave.com/?ref=WTS071/` downloaded the appropriately tagged `Brave-Browser-WTS071.pkg` file.
     * https://laptop-updates-staging.brave.com/download/WTS071 - https://referrals.brave.com/latest/Brave-Browser-WTS071.pkg
   * ensured that the referral code persists via the following:
     * `https://staging.brave.com/`
     * `https://staging.brave.com/download/`

</details>

<details>
<summary>Win 8.1 x64 - PASSED</summary>
<br>

* ensured that the new page is being displayed when using `Chrome 85.0.4183.121 (Official Build) (64-bit)`
   * ensured that clicking on `Download Brave for Windows 64-bit` downloaded `BraveBrowserSetup.exe`
     * https://laptop-updates-staging.brave.com/latest/winx64 - https://referrals.brave.com/latest/BraveBrowserSetup.exe

<img width="1232" alt="Screen Shot 2020-09-30 at 11 14 32 PM" src="https://user-images.githubusercontent.com/2602313/94761513-41809400-0373-11eb-9837-ab56fafd6046.png">

* ensured that brave.com loads the standard page (not targeting Chrome) when visiting using `de`, `zh` or `ja` locales using `Chrome 85.0.4183.121 (Official Build) (64-bit)`

| `de` | `zh` | `ja` |
| ----- | --- | ---- |
| <img width="1226" alt="Screen Shot 2020-09-30 at 11 19 31 PM" src="https://user-images.githubusercontent.com/2602313/94761585-712f9c00-0373-11eb-8f35-fc3ac8538317.png"> | <img width="1233" alt="Screen Shot 2020-09-30 at 11 20 34 PM" src="https://user-images.githubusercontent.com/2602313/94761680-a63bee80-0373-11eb-9a6f-7a1d94378ac6.png"> | <img width="1232" alt="Screen Shot 2020-09-30 at 11 22 40 PM" src="https://user-images.githubusercontent.com/2602313/94761770-dc796e00-0373-11eb-9957-228df1711746.png"> |

* visited `staging.brave.com/w0ts0n` and confirmed that referrals are working using `Chrome 85.0.4183.121 (Official Build) (64-bit)`
  * ensured `staging.brave.com/w0ts0n` redirects to `https://staging.brave.com/?ref=WTS071/`
  * ensured that clicking on `Download Brave for Windows 64-bit` on `https://staging.brave.com/?ref=WTS071/` downloaded the appropriately tagged `BraveBrowserSetup-WTS071.exe` executable.
     * https://laptop-updates-staging.brave.com/download/WTS071 - https://referrals.brave.com/latest/BraveBrowserSetup-WTS071.exe
   * ensured that the referral code persists via the following:
     * `https://staging.brave.com/`
     * `https://staging.brave.com/download/`

| `Opera 71.0.3770.198` | `IE 11.0.9600.19781` | `Edge 85.0.564.63 (Official build) (64-bit)` |
| ----- | --- | ---- |
| <img width="1314" alt="Screen Shot 2020-09-30 at 11 28 14 PM" src="https://user-images.githubusercontent.com/2602313/94762087-c5874b80-0374-11eb-9609-3122c34c10ad.png"> | <img width="1263" alt="Screen Shot 2020-09-30 at 11 36 51 PM" src="https://user-images.githubusercontent.com/2602313/94762521-f1570100-0375-11eb-9e70-b2af9c5cd606.png"> | <img width="1215" alt="Screen Shot 2020-09-30 at 11 38 34 PM" src="https://user-images.githubusercontent.com/2602313/94762616-367b3300-0376-11eb-8e6a-4354cc053c29.png"> |

* visited `staging.brave.com/w0ts0n` and confirmed that referrals are working using `Opera 71.0.3770.198`
  * ensured `staging.brave.com/w0ts0n` redirects to `https://staging.brave.com/?ref=WTS071/`
  * ensured that clicking on `Download Brave for Windows 64-bit` on `https://staging.brave.com/?ref=WTS071/` downloaded the appropriately tagged `BraveBrowserSetup-WTS071.exe` executable.
     * https://laptop-updates-staging.brave.com/download/WTS071 - https://referrals.brave.com/latest/BraveBrowserSetup-WTS071.exe
   * ensured that the referral code persists via the following:
     * `https://staging.brave.com/`
     * `https://staging.brave.com/download/`

</details>

<details>
<summary>Win 8.1 x86 - PASSED</summary>
<br>

* ensured that the new page is being displayed when using `Chrome 85.0.4183.121 (Official Build) (32-bit)`
   * ensured that clicking on `Download Brave for Windows 32-bit` downloaded `BraveBrowserSetup32.exe`
     * https://laptop-updates-staging.brave.com/latest/winia32 - https://referrals.brave.com/latest/BraveBrowserSetup32.exe

<img width="1136" alt="Screen Shot 2020-10-01 at 12 10 18 AM" src="https://user-images.githubusercontent.com/2602313/94767512-8d830700-037a-11eb-961a-9f3b25bc0232.png">

* ensured that brave.com loads the standard page (not targeting Chrome) when visiting using `ko`, `de` or `fr` locales using `Chrome 85.0.4183.121 (Official Build) (32-bit)`

| `ko` | `de` | `fr` |
| ----- | --- | ---- |
| <img width="1149" alt="Screen Shot 2020-10-01 at 12 16 24 AM" src="https://user-images.githubusercontent.com/2602313/94767759-5c570680-037b-11eb-88ef-17b79af16082.png"> | <img width="1142" alt="Screen Shot 2020-10-01 at 12 16 58 AM" src="https://user-images.githubusercontent.com/2602313/94767784-7395f400-037b-11eb-9681-8f87d0c5b5dc.png"> | <img width="1135" alt="Screen Shot 2020-10-01 at 12 17 40 AM" src="https://user-images.githubusercontent.com/2602313/94767809-89a3b480-037b-11eb-9ac0-2ee1bef56922.png"> |

* visited `staging.brave.com/w0ts0n` and confirmed that referrals are working using `Chrome 85.0.4183.121 (Official Build) (64-bit)`
  * ensured `staging.brave.com/w0ts0n` redirects to `https://staging.brave.com/?ref=WTS071/`
  * ensured that clicking on `Download Brave for Windows 32-bit` on `https://staging.brave.com/?ref=WTS071/` downloaded the appropriately tagged `BraveBrowserSetup32-WTS071.exe` executable.
     * https://laptop-updates-staging.brave.com/download/WTS071 - https://referrals.brave.com/latest/BraveBrowserSetup32-WTS071.exe
   * ensured that the referral code persists via the following:
     * `https://staging.brave.com/`
     * `https://staging.brave.com/download/`

| `FX 81.0 (32-bit)` | `Edge 85.0.564.63 (Official build) (32-bit)` | `IE 11.0.9600.19811 x86` |
| ----- | --- | ---- |
| <img width="1331" alt="Screen Shot 2020-10-01 at 12 22 35 AM" src="https://user-images.githubusercontent.com/2602313/94768103-67f6fd00-037c-11eb-8df3-b7ea7fb635ce.png"> |<img width="1220" alt="Screen Shot 2020-10-01 at 12 24 55 AM" src="https://user-images.githubusercontent.com/2602313/94768269-f9666f00-037c-11eb-97fa-dc3cf9d9fc57.png"> | <img width="1249" alt="Screen Shot 2020-10-01 at 12 27 36 AM" src="https://user-images.githubusercontent.com/2602313/94768275-fbc8c900-037c-11eb-9616-594c1db49dab.png"> |

* visited `staging.brave.com/w0ts0n` and confirmed that referrals are working using `Edge 85.0.564.63 (Official build) (32-bit)`
  * ensured `staging.brave.com/w0ts0n` redirects to `https://staging.brave.com/?ref=WTS071/`
  * ensured that clicking on `Download Brave for Windows 32-bit` on `https://staging.brave.com/?ref=WTS071/` downloaded the appropriately tagged `BraveBrowserSetup32-WTS071.exe` executable.
     * https://laptop-updates-staging.brave.com/download/WTS071 - https://referrals.brave.com/latest/BraveBrowserSetup32-WTS071.exe
   * ensured that the referral code persists via the following:
     * `https://staging.brave.com/`
     * `https://staging.brave.com/download/`

</details>

<details>
<summary>Ubuntu 20.04 x64 - PASSED</summary>
<br>

* ensured that the new page is being displayed when using `Chrome 85.0.4183.121 (Official Build) (64-bit)`
   * ensured that clicking on `Download Brave for Linux` downloaded opens the following in a new tab:
     * https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

<img width="1146" alt="Screen Shot 2020-10-01 at 12 55 09 AM" src="https://user-images.githubusercontent.com/2602313/94769833-fbcac800-0380-11eb-9d4f-4ceb34237db3.png">

* ensured that brave.com loads the standard page (not targeting Chrome) when visiting using `ja`, `zh` or `de` locales using `Chrome 85.0.4183.121 (Official Build) (64-bit)`

| `ja` | `zh` | `de` |
| ----- | --- | ---- |
| <img width="1174" alt="Screen Shot 2020-10-01 at 12 59 08 AM" src="https://user-images.githubusercontent.com/2602313/94769966-549a6080-0381-11eb-9d80-501403a746bc.png"> | <img width="1153" alt="Screen Shot 2020-10-01 at 12 59 48 AM" src="https://user-images.githubusercontent.com/2602313/94770003-6f6cd500-0381-11eb-944c-9d34e418ac3e.png"> | <img width="1168" alt="Screen Shot 2020-10-01 at 1 00 32 AM" src="https://user-images.githubusercontent.com/2602313/94770038-87dcef80-0381-11eb-8f31-d18c944d438f.png"> |

| `Chromium 85.0.4183.121 x64` | `Gnome Web 3.36.3 x64` | `FX 81.0 (64-bit)` |
| ----- | --- | ---- |
| <img width="1242" alt="Screen Shot 2020-10-01 at 1 07 03 AM" src="https://user-images.githubusercontent.com/2602313/94770363-721bfa00-0382-11eb-8b85-311a2e26c370.png"> | <img width="999" alt="Screen Shot 2020-10-01 at 1 04 55 AM" src="https://user-images.githubusercontent.com/2602313/94770270-3123e580-0382-11eb-8148-cc3342648de1.png"> | <img width="1245" alt="Screen Shot 2020-10-01 at 1 03 23 AM" src="https://user-images.githubusercontent.com/2602313/94770178-f326c180-0381-11eb-8ca7-200dec0fd2fb.png"> |

</details>

**Comment by kjozwiak** [comment]
Closing as this was completed and QA signed off. Thanks again for the hard work @LaurenWags 👍
