### ISSUE TITLE
Stephen - QA hack day

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#199]
### Profile directory locations:
`Windows`: C:\Users\yourusername\AppData\Local\BraveSoftware
`macOS`: ~/Library/Application Support/BraveSoftware/

### Issue Verification
1.19.x issues, use https://github.com/brave/brave-browser/releases/tag/v1.19.63 for issue verification

- [Desktop] Brave Today intro card should dismiss https://github.com/brave/brave-browser/issues/12960 
- Replace "Add Card" tab with sub-tab "Edit Cards" https://github.com/brave/brave-browser/issues/12625
- Use frame URL as root context when adblocking https://github.com/brave/brave-browser/issues/12737 

1.20.x issues, use https://github.com/brave/brave-browser/releases/tag/v1.20.37 for issue verification

- [Desktop] mixed content is no longer being auto-upgraded https://github.com/brave/brave-browser/issues/10190
- Blank White New Tab Page https://github.com/brave/brave-browser/issues/13039
- Autoplay blocked indicator shows up when media is not autoplayed https://github.com/brave/brave-browser/issues/13167
- [Desktop] Remove unsupported components in brave://components https://github.com/brave/brave-browser/issues/8709
- cr88 followup: Brave toolbar buttons (Bookmark, Speedreader) don't work. https://github.com/brave/brave-browser/issues/13203

#### Rewards
- Navigate to profile directory location and remove existing profile
- Open terminal
- Execute this command to launch Brave Dev using the Rewards staging environment: 
   - On `macOS`: `/Applications/Brave\ Browser\ Dev.app/Contents/MacOS/Brave\ Browser\ Dev --args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --rewards=staging=true`
   - On `Windows`: `.\brave.exe --args --enable-logging=stderr --rewards=staging=true --brave-ads-staging --vmodule=""*/bat-native-ads/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6"`
- Click on the BAT logo
- Select "Start using Brave Rewards"
- Claim the free token grant
- Once your balance updates, navigate to https://laurenwags.github.io
- Click on the BAT logo
- Select "Send a tip"
- Choose an amount and send the tip

#### Shields
- Navigate to https://nytimes.com.
- Open the Brave Shields for this site
- Allow all trackers and ads
- Confirm ads are now visible on this site
- Open Brave Shields again
- Change to standard protection for trackers and ads
- Confirm ads are no longer shown on this site
- Navigate to https://www.blizzard.com
- Open Brave Shields for this site
- Block scripts
- Confirm scripts are blocked on this site

#### Geolocation
- Navigate to https://browserleaks.com/geo
- Allow the site to access your location
- Confirm (approximate) location is shown

#### Tor Tabs
- Open a Tor Window
- Navigate to https://check.torproject.org
- Confirm a success message is shown, confirming Tor network is being utilized
- Navigate to https://brave.com
- Click on Onion Available
- Confirm Brave's onion site opens in a new tab

**Comment by kjozwiak** [comment]
Closing 👍 Thanks for creating the above @LaurenWags. Awesome job.
