### ISSUE TITLE
Re-testing old sync issues via backlog

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#213]
#### Release Date/Target:

* Release Date: **`N/A`** (whenever time permits, check an issue here and there till backlog empty)

#### Summary:

@jsecretan has requested QA to run through the opened sync issues via the following backlog:

* https://github.com/orgs/brave/projects/1#column-10569566

Priority isn't high but QA will need to run through issues whenever we have some time available and slowly work our way through the list.

**Comment by LaurenWags** [comment]
@kjozwiak can this be closed as stale?

**Comment by kjozwiak** [comment]
> @kjozwiak can this be closed as stale?

@LaurenWags yup, lets close this off. @AlexeyBarabash just went through a bunch of stale/older ones and reached out to QA when needed. So technically, the above has been completed. Looks like there's only https://github.com/brave/brave-browser/issues/16488 left via https://github.com/orgs/brave/projects/1#card-63519177.

**Comment by AlexeyBarabash** [comment]
:+1: thanks @kjozwiak @LaurenWags
