### ISSUE TITLE
Brave Wallet release for milestone 1.0.26

### ISSUE THREAD

**Issue by bbondy** [brave/qa-resources#222]
#### Release Date/Target:

* Release Date: ASAP, Feb 9th?

#### Summary:

Crypto Wallets release candidate 1.0.23 targeting the milestone 1.0.26 is available via: https://go-updater-dev.bravesoftware.com/extensions/test

https://github.com/brave/brave-browser/milestone/175?closed=1

#### Related GH issues/Documentation:
https://github.com/brave/brave-browser/wiki/Crypto-Wallets

**Comment by kjozwiak** [comment]
@bbondy believe we've pushed out `1.0.26`. Closing but please re-open if that's not the case.
