### ISSUE TITLE
Translation checks

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#238]
#### Release Date/Target:

* Release Date: TBD 

#### Summary:

Retest items under the "Retest" column of General board to confirm translation issues fixed. 

#### Related GH issues/Documentation:

https://github.com/brave/brave-browser/projects/9 cc @rebron to add issues to this column for testing

**Comment by btlechowski** [comment]
All the issues from `Retest` were retested.

![image](https://user-images.githubusercontent.com/34715963/112367681-878f3280-8cda-11eb-90c6-a5f5aea70315.png)

**Comment by LaurenWags** [comment]
great, thanks for getting this done @btlechowski 👍🏻
