### ISSUE TITLE
1.21.x Release 3

### ISSUE THREAD

**Issue by bsclifton** [brave/qa-resources#247]
#### Release Date/Target: 

* Release Date: **`Thursday March 11, 2021`**

#### Summary:

Includes the following features/fixes:

* Minor Chromium bump (`89.0.4389.86`) https://github.com/brave/brave-browser/pull/14580
* BAP => BAT messaging https://github.com/brave/brave-core/pull/8178

**Milestone:**
https://github.com/brave/brave-browser/milestone/181
https://github.com/brave/brave-core/milestone/126

**Current Progress:**

* macOS -->
* Win-->
* Linux -->

**Manual Passes:**

* macOS x64 --> **Completed** ~~https://github.com/brave/brave-browser/issues/14586~~
* macOS Arm64 --> **Completed** ~~https://github.com/brave/brave-browser/issues/14584~~
* Win --> **Completed** ~~https://github.com/brave/brave-browser/issues/14585~~
* Linux --> **Completed** ~~https://github.com/brave/brave-browser/issues/14587~~

**Comment by srirambv** [comment]
Completed and released
