### ISSUE TITLE
1.21.x Release 3

### ISSUE THREAD

**Issue by bsclifton** [brave/qa-resources#248]
#### Release Date/Target:

* Release Date: **`Thursday March 11, 2021`**

#### Summary:

Includes the following features/fixes:

* Minor Chromium bump (`89.0.4389.86`) https://github.com/brave/brave-browser/pull/14580
* BAP => BAT messaging https://github.com/brave/brave-core/pull/8178

**Milestone:**
https://github.com/brave/brave-browser/milestone/181
https://github.com/brave/brave-core/milestone/126

**Current Progress:**

* ARM -->
* Tablet -->
* x86 -->

**Manual Passes:**

* ARM --> **Completed** ~~https://github.com/brave/brave-browser/issues/14597~~
* Tablet --> **Completed** ~~https://github.com/brave/brave-browser/issues/14598~~
* x86 -->**Completed**  ~~https://github.com/brave/brave-browser/issues/14599~~

**Comment by srirambv** [comment]
Release complete. Closing the issue
