### ISSUE TITLE
Tor 1.0.15 (0.4.5.7) component update

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#254]
#### Release Date/Target:

* Release Date: **`Thursday March 18, 2021`** 

#### Summary:

Update the Tor component. We'll get more information tomorrow (March 16th) once released.

**Milestone:**

https://github.com/brave/brave-browser/milestone/184

**Current Progress:**

* macOS --> **`0`** verification remaining
* Win--> **`0`** verification remaining
* Linux --> **`0`** verification remaining

**Manual Passes:**

* macOS x64 --> ~~https://github.com/brave/brave-browser/issues/14745~~ **`Completed`**
* Win --> ~~https://github.com/brave/brave-browser/issues/14744~~ **`Completed`**
* Linux --> ~~https://github.com/brave/brave-browser/issues/14746~~ **`Completed`**

**Comment by LaurenWags** [comment]
This was released to production on Thursday March 18, 2021 via call with @jumde @kjozwiak @stephendonner @LaurenWags
