### ISSUE TITLE
Testing TLS pinning with MITM software

### ISSUE THREAD

**Issue by fmarier** [brave/qa-resources#295]
#### Release Date/Target:
* Release Date: 1.27

#### Summary:
I just enabled TLS pinning on Nightly. That means that if any of the [affected hostnames](https://github.com/brave/brave-core/blob/c716d44d3d5eed8080e8c2b865be3dfd1d80c816/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc#L414-L471) start to use a different certificate authority than [the ones we allow](https://github.com/brave/brave-core/blob/c716d44d3d5eed8080e8c2b865be3dfd1d80c816/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc#L390-L403) then these requests will fail:
![Screenshot from 2021-05-28 16-55-24](https://user-images.githubusercontent.com/167821/120051446-88438e00-bfd5-11eb-858f-7553620b8620.png)

One thing that could cause problems with this is security software (e.g. A/V) which performs a MITM on the traffic and replaces the certificates. Here is how dveditz suggested testing a similar feature in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1308251#c67

#### Related GH issues/Documentation:
https://github.com/brave/brave-core/pull/8750
https://github.com/brave/brave-browser/issues/15667
https://github.com/brave/brave-browser/issues/12349
https://github.com/brave/brave-browser/issues/2949

**Comment by fmarier** [comment]
I did do a quick test with [mitmproxy](https://mitmproxy.org/):
```
mitmproxy --mode socks5 --listen-port 9000
npm run start -- --proxy-server="socks5://localhost:9000"
```
and everything looked normal.

**Comment by kjozwiak** [comment]
@fmarier just noticed this right now. Should this be checked on `1.27.x` before the `June 15, 2021` migration?

**Comment by fmarier** [comment]
It could be checked before or after the migration of 1.27 to beta, but before 1.27 goes to release (so that there's time to revert if needed).

I've tested it as much as I could, but I was wondering if QA had access to more test environments that might be TLS-hostile. For example, enterprise MITM, A/V software, etc. This is probably only relevant for Windows.

**Comment by fmarier** [comment]
The version of AVG that @GeetaSarvadnya used in https://github.com/brave/brave-browser/issues/15667#issuecomment-873902274 might be useful for this test.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.27.107 Chromium: 92.0.4515.107 (Official Build) (64-bit)
--- | ---
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2009 (Build 19043.1081)
```

**`No MITM (PASSED)`** | **`MITM via AVG (FAILED)`**
---------------------------|---------------------------------
![win10Passed](https://user-images.githubusercontent.com/2602313/126707263-fca7aaad-dbb9-4b6f-8de1-04abe1a1c979.png) | ![win10Failed](https://user-images.githubusercontent.com/2602313/126707269-2f66d829-617a-444c-b4f1-f138a3841d95.png)

-------------------

Verification **PASSED** on `Win 10 x86` using the following build:

```
Brave | 1.27.107 Chromium: 92.0.4515.107 (Official Build) (32-bit)
--- | ---
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2009 (Build 19043.1081)
```

**`No MITM (PASSED)`** | **`MITM via AVG (FAILED)`**
---------------------------|---------------------------------
![image](https://user-images.githubusercontent.com/2602313/126707840-4c2b1755-85f9-4cba-ad62-754f3ca378c7.png) | ![image](https://user-images.githubusercontent.com/2602313/126707785-8e671dce-ee54-45b6-83e5-25f6f7523ca3.png)

**Comment by kjozwiak** [comment]
Closing 👍 QA ensured that pinning fails when a MITM cert is detected as per https://github.com/brave/qa-resources/issues/295#issuecomment-885225552. We also ran through the cases outlined via https://github.com/brave/brave-core/pull/8750#issue-633758318 as per https://github.com/brave/brave-browser/issues/15667#issuecomment-852442480.
