### ISSUE TITLE
Crypto Wallets 1.0.32 hotfix release

### ISSUE THREAD

**Issue by bbondy** [brave/qa-resources#336]
#### Release Date/Target:

* Release Date: ASAP

#### Summary:

Crypto Wallets release candidate 1.0.32 is ready for testing on: https://go-updater-dev.bravesoftware.com/extensions/test

When it goes to the prod server it will be 1.0.32
On the dev server it is 1.0.35
https://github.com/brave/ethereum-remote-client/releases/tag/0.1.96

This includes:

This PR fixes the following issues:
* https://github.com/brave/brave-browser/issues/16760
* https://github.com/brave/brave-browser/issues/16750
* https://github.com/brave/brave-browser/issues/16983

**Milestone:**

https://github.com/brave/brave-browser/milestone/219

**Current Progress:**

* macOS --> **Completed**
* Win-->  **Completed**
* Linux --> **Completed**

**Manual Passes:**

* macOS x64 --> ~~https://github.com/brave/brave-browser/issues/16993~~
* Win --> NA
* Linux --> NA

**Comment by srirambv** [comment]
QA singed off and released
