### ISSUE TITLE
Update Test script for Native Crypto Wallet and Update Wikitemplate_Crypto to include native wallet changes

### ISSUE THREAD

**Issue by srirambv** [brave/qa-resources#341]
Since native wallet will be part of brave-core releases and not every bc release may have CWallet work, here's my recommendations

1. Create a separate test runs for CW in the same b-c milestone along with issue verification's from that milestone
2. Create a separate regression test suite independent of the desktop test run that can be generated and tested along with bc test runs
2. Create a separate test suite for HF/sanity checks where ever applicable that can be checked for minor CR bump releases (only if required)

Would be good to keep them separate from bc regression manual pass as that itself is pretty huge. 

cc: @bbondy

**Comment by bbondy** [comment]
It doesn't matter to me how it's organized but so long as it's considered a normal part of brave-core and so should follow the same rules.  I suggest if things are getting too big to maybe do a link of sub-sheets that must be run or something along those lines.

**Comment by srirambv** [comment]
Will be adding a Wallet regression testsheet to generate test runs for major CR bumps.
