### ISSUE TITLE
Update  `https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/`

### ISSUE THREAD

**Issue by srirambv** [brave/qa-resources#373]
@stephendonner could also do https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/

_Originally posted by @wknapik in https://github.com/brave/qa-resources/pull/371#discussion_r716985786_

**Comment by stephendonner** [comment]
Am I supposed to replace the link, or add it?

**Comment by srirambv** [comment]
I believe its supposed to be replaced. @wknapik can confirm though

**Comment by wknapik** [comment]
I was thinking of testing both https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/ and https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/ - one is for the brave.com site, the other is for search.

But it's up to you, that was just a suggestion.

**Comment by stephendonner** [comment]
Landed.
