### ISSUE TITLE
QA of new brave.com homepage

### ISSUE THREAD

**Issue by rmcfadden3** [brave/qa-resources#381]
#### Release Date/Target:
We need to publish the new homepage on Tuesday, Oct 19, to coincide with the Search default announcement. So ideally QA is done by EOD Friday, Oct 15, or morning of Monday, Oct 18 at the latest.

#### Summary:
We have a brand new version of the brave.com homepage staged at staging.brave.com. Localizations should already be back and uploaded as well. The only functionality which should need verification is download buttons. Apart from that, general checks on responsiveness in various devices and browsers.

Also: Note that users arriving from Chrome should see a slightly different tagline in the hero plank ("3x faster than Chrome. Better protection from Google.") For all other browsers, users should see "Browse privately. Search privately. And beat Big Tech."

Otherwise all other copy / functionality on the 2 page variants should be identical.

#### Related GH issues/Documentation:
None

CC @AlanBreck & @josece & @Dmkeller

**Comment by stephendonner** [comment]
Got it; starting with this commit on October 11: https://github.com/brave/brave-com/commit/1ea5947cf2239e6738935f53eb88c6d71410f749

**Comment by stephendonner** [comment]
Verified `PASSED` using

Desktop (both macOS and Windows - spot-checked on Linux):
* Google Chrome 94.0.4606.81
* Apple Safari  15.0 (16612.1.29.41.4, 16612)
* Mozilla Firefox 93
* Microsoft Edge 94.0.992.50

Mobile:
* Apple Safari on iOS 15.1 public beta
* Google Chrome 94.0.4606.76 on iOS 15.1 public beta
* Google Chrome 66.0.3359.158 on Android 9
* Mozilla Firefox Daylight 38.1 (6216) on iOS 15.1 public beta

Confirmed:
* responsive design on desktop + mobile
* different messaging and video for Chrome browsers vs. all others (see below)
* reported and verified fixed a z-index issue on Firefox with the `Download Brave` buttons

`3x faster than Chrome...` | `Browse privately...`
---------|--------
![Screen Shot 2021-10-18 at 12 21 52 PM](https://user-images.githubusercontent.com/387249/137793828-f121fe93-c43a-4d0b-a135-edc8bd61ffb0.png) | <img width="1680" alt="Screen Shot 2021-10-18 at 12 22 30 PM" src="https://user-images.githubusercontent.com/387249/137793842-116d7e16-db46-40f5-87b0-a96b1d333905.png">
