### ISSUE TITLE
QA for download interstitial page on brave.com

### ISSUE THREAD

**Issue by rmcfadden3** [brave/qa-resources#391]
#### Release Date/Target:
We don't have a solid release date yet, but likely sometime in late Jan / early Feb.

Note that we'd like QA on the final page design, but also to get QA help on establishing the specific set of download instructions (and thus the copy) for each browser / OS combo. This will make more sense when you see the design below.

#### Summary:
We're building a download interstitial page on brave.com. The idea is, after you click "Download" anywhere on brave.com, you'd see an interstitial page with instructions on where to find the download package, and how to complete the install. Goal here is to reduce the attrition we see where people download but don't complete install. Basically to improve conversion.

#### Related GH issues/Documentation:
See Ryan for source doc & Figma.

CC @Dmkeller & @AlanBreck & @laurentiugruia

**Comment by LaurenWags** [comment]
Reference materials: https://bravesoftware.slack.com/archives/GAA4017R7/p1647358455106379

cc @kjozwiak @stephendonner @MadhaviSeelam @GeetaSarvadnya

**Comment by LaurenWags** [comment]
This was completed on April 6 per https://github.com/brave/brave-com/pull/600
