### ISSUE TITLE
Add Tor DNS leak checks 

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#394]
We'll need to add Tor DNS leak checks under our full manual passes as per @diracdeltas. We've had several instances of this happening before and still get reports from time to time. Sometimes they're valid and sometimes they're not. Either way, we should have it in our manual passes so the chances of this happening/being unnoticed is reduced.

**Comment by stephendonner** [comment]
@kjozwiak fixed in https://github.com/brave/qa-resources/commit/20f7ce402a54800d066fdb45357d8c2b74038f4e, or should we add more/tweak?

**Comment by kjozwiak** [comment]
> @kjozwiak fixed in [20f7ce4](https://github.com/brave/qa-resources/commit/20f7ce402a54800d066fdb45357d8c2b74038f4e), or should we add more/tweak?

I think that's good enough, we can probably close this off and add more if needed in the future.
