### ISSUE TITLE
Greaselion 1.1.0

### ISSUE THREAD

**Issue by zenparsing** [brave/qa-resources#423]
#### Release Date/Target:

* Release Date: **`April 18, 2022 (approximately)`**

#### Summary:

Includes:

* https://github.com/brave/brave-site-specific-scripts/pull/69

**Milestone:**

* https://github.com/brave/brave-browser/milestone/280

**Current Progress:**

* macOS --> Completed via https://github.com/brave/brave-browser/issues/12900#issuecomment-1100167370
* Win--> Completed via https://github.com/brave/brave-browser/issues/12900#issuecomment-1100197813
* Linux --> completed via https://github.com/brave/brave-browser/issues/12900#issuecomment-1100269216

**Manual Passes:**

N/A

**Comment by LaurenWags** [comment]
Completed on April 15, 2022, signed off via https://bravesoftware.slack.com/archives/C212VB0RG/p1650047931214899
