### ISSUE TITLE
Test universal builds for macOS so that we can offer a simplified download page

### ISSUE THREAD

**Issue by bsclifton** [brave/qa-resources#438]
#### Release Date/Target:
Tentatively marked as a P2; no explicit date... but this would help provide a much more clear user-experience for macOS users who are looking to download Brave.

The binaries can be deployed at any given time and then (when tested) we can stand up a landing page. 

#### Summary:
The macOS download page currently has a split flow; where user needs to pick their architecture. This can be confusing

@mihaiplesa has universal binaries available for testing here (Slack link, for employees):
https://bravesoftware.slack.com/archives/C01EVLWS8R5/p1652386718879259

Per @LaurenWags we'll want to try a few tests:
- Install from universal build
- Confirm you receive correct version of x64 vs arm64, perhaps via brave://version/
- Check that you are able to upgrade to a new version (provided one exists) and after upgrade you still have the correct version (x64 or arm64)

At the moment, upgrades are not possible. But we can do this with an internal channel when ready. More information in the `#macos` Slack channel for employees.

#### Related GH issues/Documentation:
We do have some issues intended to simplify this (which haven't been picked up yet):
- [auto-detect the OS on download landing page](https://github.com/brave/brave-com-resources/issues/475)
- [Stub installer for brave-core](https://github.com/brave/brave-browser/issues/20849) (where universal installer would run and detect OS, download/install native version based on arch)

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using builds noted below.

| File Type | Installation | Version | Widevine |   |
|-----------|--------------|---------|----------|---|
|  `.dmg`      |              |         |          |   |
|  `.pkg`     |              |         |          |   |
|           |              |         |          |   |

**Comment by kjozwiak** [comment]
### macOS 10.11.6 OS X El Captain x64

<details>
<summary>installed 1.40.52 Chromium: 101.0.4951.64 via .dmg - PASSED</summary>

```
Brave | 1.40.52 Chromium: 101.0.4951.64 (Official Build) nightly (x86_64)
--- | ---
Revision | d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}
OS | OS X Version 10.11.6 (Build 15G22010)
```

* ensured that `x86_64` was being installed
* ensured that `nightly` is being used/mentioned via `brave://version` & `brave://settings/help`
* restarted the browser several times and ensured there were no issues/obvious crashes
* ensured that updating from `1.40.52 Chromium: 101.0.4951.64` -> `1.41.14 Chromium: 102.0.5005.61` didn't cause any issues

**`Widevine:`**

* downloaded `Widevine Content Decryption Module - Version: 4.10.2391.0` when enabling `Widevine` initially
* ensured that viewing media via `Netflix` worked without any issues
* restarted the browser and pulled `Widevine Content Decryption Module - Version: 4.10.2449.0`
* ensured that viewing media via `Netflix` worked without any issues (using ` 4.10.2449.0`)
* restarted the browser several times and ensured there weren't any new `Widevine` updates available
</details>

---------------

Looks like all the universal `.pkg` installations are crashing on startup on the following macOS versions:

* `OS X 10.11.6 El Catpain x64` - **FAILED** (crashed on startup)
* `macOS 10.12.6 Sierra x64` - **FAILED** (crashed on startup)
* `macOS 10.13.6 High Sierra x64` - **FAILED** (crashed on startup)

Builds/packages being used:

* [1.40.52 - Nightly](https://brave-jenkins-build-artifacts.s3.us-west-2.amazonaws.com/brave-browser/v1.40.52/Brave-Browser-Nightly-universal.pkg) - **CRASHED** on startup
* [1.39.102 - Dev](https://brave-jenkins-build-artifacts.s3.us-west-2.amazonaws.com/brave-browser/v1.39.102/Brave-Browser-Dev-universal.pkg) - **CRASHED** on startup
* [1.39.101 - BETA](https://brave-jenkins-build-artifacts.s3.us-west-2.amazonaws.com/brave-browser/v1.39.101/Brave-Browser-Beta-universal.pkg) - **CRASHED** on startup
* [1.38.115 - Release](https://brave-jenkins-build-artifacts.s3.us-west-2.amazonaws.com/brave-browser/v1.38.115/Brave-Browser-universal.pkg) - **CRASHED** on startup

I double checked and ensured that our current `.pkg` are working as expected using the following:

* [1.39.111 Chromium 102.0.5005.61](https://github.com/brave/brave-browser/releases/download/v1.39.111/Brave-Browser-x64.pkg) - **PASSED** & launched on startup
* [1.40.74 Chromium 102.0.5005.61](https://github.com/brave/brave-browser/releases/download/v1.40.74/Brave-Browser-Beta-x64.pkg) - **PASSED** & launched on startup
* [1.41.15 Chromium 102.0.5005.61](https://github.com/brave/brave-browser/releases/download/v1.41.15/Brave-Browser-Nightly-x64.pkg) - **PASSED** & launched on startup

Example of what I'm seeing via the terminal:

```
osx-10:~ kjozwiak$ /Applications/Brave\ Browser\ Dev.app/Contents/MacOS/Brave\ Browser\ Dev --disable-gpu
chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[0525/224744.340031:ERROR:file_io.cc(94)] ReadExactly: expected 8, observed 0
[0525/224744.341906:ERROR:crash_report_database_mac.mm(104)] mkdir : No such file or directory (2)
Trace/BPT trap: 5
```

<img width="615" alt="Screen Shot 2022-05-25 at 10 47 58 PM" src="https://user-images.githubusercontent.com/2602313/170405512-69ebbb67-ed75-4578-aa06-b71f8779df9f.png">

<img width="1156" alt="Screen Shot 2022-05-25 at 11 01 24 PM" src="https://user-images.githubusercontent.com/2602313/170407032-308f4f28-e1aa-4f8c-9052-8267c1ea6bf3.png">

**Comment by LaurenWags** [comment]
Verification in progress using macOS Monterey 12.3.1 arm64/M1.

**Comment by LaurenWags** [comment]
#### Verification in progress using macOS Monterey 12.4 x64/Intel

<details>
<summary>Installed 1.40.52 Chromium: 101.0.4951.64 (nightly) via .dmg - InProgress</summary>

```

```

* ensured that `arm64` was being installed
* ensured that `nightly` is being used/mentioned via `brave://version` & `brave://settings/help`
* restarted the browser several times and ensured there were no issues/obvious crashes
* ensured that updating from `1.40.52 Chromium: 101.0.4951.64` -> `1.41.17 Chromium: 102.0.5005.61` didn't cause any issues
* note, after update version is now the Apple Silicon one (see screenshot below)

**`Widevine:`**

* downloaded `Widevine Content Decryption Module - Version: 4.10.2391.0` when enabling `Widevine` initially
* ensured that viewing media via `Netflix` worked without any issues
* restarted the browser and pulled `Widevine Content Decryption Module - Version: 4.10.2449.0`
* ensured that viewing media via `Netflix` worked without any issues (using ` 4.10.2449.0`)
* restarted the browser several times and ensured there weren't any new `Widevine` updates available

Universal build being installed | arm64 version being used | brave://settings/help | Update installed | After Update
----- | ----- | ----- | ----- | ----- 


</details>
