### ISSUE TITLE
Update geolocation on test plans

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#44]
Due to https://github.com/brave/browser-laptop/issues/12692#issuecomment-358481465 we should update the geolocation part of test plans.

**Comment by kjozwiak** [comment]
Thanks for creating this @LaurenWags! It looks like chromium deprecated [geolocation permissions from cross-origin iframes](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes). Perhaps we can use:

https://html5demos.com/geo/
