### ISSUE TITLE
Fix or delete jsfiddle-based (defunct) Fingerprinting test

### ISSUE THREAD

**Issue by stephendonner** [brave/qa-resources#447]
Summary: Fix or delete jsfiddle-based (defunct) Fingerprinting test

https://github.com/brave/qa-resources/blob/0112e7a1504cac6f7cebd82055d569349bf97e7c/wikitemplate.md#fingerprint-tests

The following test, linked above, has caused QA confusion:

`Visit https://jsfiddle.net/bkf50r8v/13/, ensure 3 blocked items are listed in Shields. Result window should show got canvas fingerprint 0 and got webgl fingerprint 00`

@pes10k can we delete (or replace) this seemingly-defunct test?

(QA-team thread here: https://bravesoftware.slack.com/archives/GAA4017R7/p1646184521430509)

**Comment by pes10k** [comment]
Yep, its fine to delete this test.  We now cover the fingerprinting endpoints we care about in the https://dev-pages.brave.software/ tests

**Comment by stephendonner** [comment]
Fixed by https://github.com/brave/qa-resources/pull/458
