### ISSUE TITLE
Add TLS cert pinning to the QA smoketests

### ISSUE THREAD

**Issue by fmarier** [brave/qa-resources#450]
I discovered that TLS pinning [recently broke due to a Chromium update](https://github.com/brave/brave-browser/issues/24451).

We should add a quick manual test when we do a release:

1. Open <https://ssl-pinning.someblog.org/>
2. Verify that you get a pinning error:
![Screenshot from 2022-08-04 15-46-29](https://user-images.githubusercontent.com/167821/182975351-5c40eb35-b542-4198-86e8-620abe826af3.png)

**Comment by LaurenWags** [comment]
@fmarier is this only applicable to desktop or should we be checking this for Android as well?

**Comment by fmarier** [comment]
It's not currently enabled on Android. So desktop-only for now.
