### ISSUE TITLE
Add check to ensure nothing unexpected is added into the hamburger menu

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#453]
We'll need to add some manual checks to make sure that nothing is being added into the main hamburger menu that's not expected. For example, Brave Talk was added via https://github.com/brave/brave-browser/issues/24587 and was shipped with `1.42.x`. However, because the issue didn't have a milestone/labels, QA didn't run through the STR/Cases (which were also missing).

In this scenario, if we would have noticed Brave Talk within the menu and ran through the passes, we would have noticed that there's a new item added but there's no associated issue within the milestone so QA can raise a red flag via Slack.

**Comment by Uni-verse** [comment]
Completed per https://github.com/brave/qa-resources/commit/629eb6c8869538f62911233f49b2f2f5df814126

Didn't open PR but will do so moving forward.
