### ISSUE TITLE
Update Android Template

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#49]
Android Test Template updates needed:
1. Bravery Settings - update Safe Browsing steps as 'Not Implemented Yet'
2. Bravery Settings - update Safe Browsing URL from downloadme.org to raisegame.com
3. Download - http/https pdf to download section from content section

**Comment by srirambv** [comment]
Also need to replace downloadme.org with risegame.com

**Comment by LaurenWags** [comment]
Yes, good call @srirambv - will do that here too 😄

**Comment by srirambv** [comment]
Also we can move the http/https pdf to download section from content section since it doesn't load in-browser

**Comment by LaurenWags** [comment]
Updated desc to match comments
