### ISSUE TITLE
IPFS component 0.16.0 for arm64

### ISSUE THREAD

**Issue by cypt4** [brave/qa-resources#491]
#### Release Date/Target: Nothing on fire

* Release Date: 

#### Summary:
Adds additional binary for arm linux 64

**Comment by mihaiplesa** [comment]
Testing this can be done using any Linux VM in Parallels on a M1/M2 Mac. Haven't tried Raspberry Pi or similar yet.

**Comment by mihaiplesa** [comment]
Related https://github.com/brave/brave-core-crx-packager/pull/504
Related https://github.com/brave/devops/pull/8548

**Comment by mihaiplesa** [comment]
Testing in Ubuntu 22 in Parallels gives the below - still tries to install amd64 version instead of arm64.

<img width="1710" alt="Screenshot 2022-10-26 at 14 51 57" src="https://user-images.githubusercontent.com/907672/198019080-cd2c3bc2-565c-458a-a351-72bebab88dff.png">

**Comment by mihaiplesa** [comment]
Made it work on the development `go-update` environment and with a build from https://github.com/brave/brave-core/pull/15673

https://github.com/brave/brave-core-crx-packager/pull/504, https://github.com/brave/go-update/pull/68 and https://github.com/brave/devops/pull/8548 were also needed.

<img width="1710" alt="Screenshot 2022-10-26 at 22 23 36" src="https://user-images.githubusercontent.com/907672/198117858-b3650006-a3c1-4a88-ac16-c165bbb9bbbc.png">

**Comment by mihaiplesa** [comment]
This will go out today in public nightly.

**Comment by srirambv** [comment]
This should be ok to close since we shipped IPFS component on Linux arm64. @mihaiplesa let me know if we still want to keep this open

**Comment by mihaiplesa** [comment]
Good to close from my side.
