### ISSUE TITLE
Refresh Rewards test cases on Desktop and Android

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#495]
Rewards test cases (on desktop and android) could use a refresh, it's been awhile since they've been updated.

Affected Desktop templates:
- [ ] `Rewards` (entire list) - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Desktop/wikitemplate.md
- [ ] `Rewards` (entire list) - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Desktop/Reduced/wikitemplate-ReducedDesktop.md

Affected Android templates:
- [ ] Rewards specific portion of `Brave Rewards/Ads` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Android/wikitemplate-android.md
- [ ] Rewards specific portion of `Brave Rewards/Ads` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Android/wikitemplate-ReducedAndroid.md

Did not update the following at this time:

Desktop templates:
- Rewards sub-section of `Upgrade` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Desktop/wikitemplate.md
- Rewards sub-section of `Upgrade` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Desktop/Reduced/wikitemplate-ReducedDesktop.md
- Rewards sub-section of `Upgrade` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Desktop/Minor_CR_Bump/wikitemplate-minorCRbump-macOS-arm64.md
- Rewards sub-section of `Upgrade` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Desktop/Minor_CR_Bump/wikitemplate-minorCRbumpDesktop.md
- Rewards sub-section of `Upgrade` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Desktop/Major_CR_Bump/wikitemplate-majorChromiumBumpUpgrades.md

Android templates:
- Rewards sub-section of `Upgrade Cases` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Android/wikitemplate-android.md
- Rewards sub-section of `Upgrade` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Android/wikitemplate-ReducedAndroid.md
- Rewards sub-section of `Upgrade` - https://github.com/brave/qa-resources/blob/master/WikiTemplate/Android/wikitemplate-minorCRbumpAndroid.md

**Comment by Uni-verse** [comment]
@Uni-verse
