### ISSUE TITLE
Update iOS issue template to include if an issue exists in the current release

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#496]
Update https://github.com/brave/brave-ios/blob/development/.github/ISSUE_TEMPLATE/new-issue.md and add a section re: if the newly created issue is a new regression or an issue that already exists in the current released version but was found when running through verification after the fact.

@srirambv @Uni-verse assigned the both of you. Should be a quick fix. If you do end up taking the above, please mention it in the comment so we're not duplicating work. Should be similar to what we have on the `Android` & `Desktop` templates.

**Comment by srirambv** [comment]
PR here https://github.com/brave/brave-ios/pull/6671
