### ISSUE TITLE
Review Web3 Brave Talk

### ISSUE THREAD

**Issue by mrose17** [brave/qa-resources#521]
#### Release Date/Target:
April 21, 2023

* Release Date: May 1, 2023

#### Summary:
The code and security reviews for Web3 Brave Talk should be completed on Monday, April 17 ... At that time, it will be available for QA on the `dev` server: https://talk.brave.software/ ... I plan to update this issue when that's done.

#### Related GH issues/Documentation:
Please see the spec https://docs.google.com/document/d/193d9IQa33QfnxHnSW-lrv3PgjW2ztZXQuSqQW3nxVYU

**Comment by kjozwiak** [comment]
@srirambv can we close this off? I know you're still running through some of the new changes for `Web3 Brave Talk`. We can either close the above off as the initial work was completed. Or we can keep it opened till we're live.

**Comment by mrose17** [comment]
We're doing the final run-through tomorrow...

**Comment by srirambv** [comment]
Yes this can be closed as completed.
