### ISSUE TITLE
Replace `LastPass` with `1Password` in Chrome Web Store test

### ISSUE THREAD

**Issue by stephendonner** [brave/qa-resources#537]
Summary: Replace `LastPass` with `1Password` in Chrome Web Store test

In the following tests, both `AdBlock Plus` and `LastPass` extensions only request 1 permission (and, the same one).

Perhaps it would be better to replace the latter w/`1Password`?  (Or similar?)

<img width="788" alt="Screen Shot 2023-09-12 at 4 57 13 PM" src="https://github.com/brave/qa-resources/assets/387249/df8ff213-67f7-48b7-ad7c-d953ebcc3046">

`AdBlock Plus` | `LastPass`
----------------|----------
<img width="1242" alt="Screen Shot 2023-09-12 at 4 56 09 PM" src="https://github.com/brave/qa-resources/assets/387249/23700778-583e-4434-a477-dee12d4f1ca3"> | <img width="1242" alt="Screen Shot 2023-09-12 at 4 56 24 PM" src="https://github.com/brave/qa-resources/assets/387249/071ac4d1-8fc8-481b-8dd8-d2a5a0e40bcc">

Suggestion:

Replace `LastPass` with `1Password`, which has quite a few more requested app/device permissions: (more to potentially go awry)

<img width="1242" alt="Screen Shot 2023-09-12 at 4 56 46 PM" src="https://github.com/brave/qa-resources/assets/387249/8a30412a-c8f6-48fa-8944-098db40dea26">

If agreed, I'll take and fix this issue 👍 

/cc @LaurenWags @kjozwiak @srirambv @btlechowski

**Comment by srirambv** [comment]
The permission list depends from extension to extension, so yeah good suggestion to replace one of them which has more requests
