### ISSUE TITLE
Possibly add "Query Filter" tests to Android full manual pass

### ISSUE THREAD

**Issue by LaurenWags** [brave/qa-resources#563]
Possibly add same test from https://github.com/brave/qa-resources/issues/535 / https://github.com/brave/qa-resources/pull/562 to Android full manual pass.

@Uni-verse to confirm before it gets added.

**Comment by kjozwiak** [comment]
@LaurenWags chatted with @fmarier and we'll need to add the above into the `Android` pass as well. Mind adding/creating a PR for `Android` as well?
