### ISSUE TITLE
Changing `pkg` -> `dmg` on `brave.com`

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#582]
#### Summary:

QA will run through the `brave.com` staging website via `https://bravesoftware.com` and ensure that the correct executables are being served for each platform. Specifically ensuring that `pkg` are being replaced with `dmg` for `macOS`. We'll also ensure that the referral codes are being added into `brave://local-state` and that there's no referral code within the executable name.

* `macOS arm64` - @LaurenWags will run through `Safari` & `Chrome`
* `Win x86` - @LaurenWags will run through `Firefox` & `Edge`
* `macOS x64` - @kjozwiak will run through `Firefox` & `Chrome`
* `Win x64` - @kjozwiak will run through `Firefox` & `Chrome`

For each of the above checks, we'll ensure that:

* `dmg` is being served/downloaded instead of `pkg` on `macOS` platforms
* ensure that the `dmg` executable doesn't have the referral code within the executable name (like we did with `pkg`)
* ensure that `universal` builds are being served and the correct architecture is being installed (`arm64` vs `x64`)
* ensure that `Win` is still serving the `stub` installers with the referral code within the name and downloading the correct architecture
* ensure that `Linux` is still pointing to `https://brave.com/linux`

#### Related GH issues/Documentation:

QA re: ensuring that the `dmg` executables were working was done via https://github.com/brave/brave-browser/issues/32316#issuecomment-1788407943, https://github.com/brave/brave-browser/issues/32316#issuecomment-1789601030 & https://github.com/brave/brave-browser/issues/32316#issuecomment-1789640524.

**Comment by LaurenWags** [comment]
Verification in progress with macOS 14.x arm64

<details>
<summary>Safari - PASSED</summary>

Using Safari (version 17.4 (19618.1.13.11.5))
- navigated to bravesoftware.com, entered credentials from 1PW
- clicked on "Download" button on main page
   - confirmed downloaded the .dmg file, not .pkg
   - confirmed no ref code appended to the .dmg file
- installed the .dmg file
   - confirmed able to install without issue
   - confirmed the .dmg installed the "Universal" version
   - confirmed current RC version 1.63.164 was installed
- visited brave://local-state
   - confirmed expected ref code (BRV002) was listed
- closed browser, deleted application, profile, and downloaded file
- spot checked the above for other ways to download:
   - "Download" button in the page header
   - bravesoftware.com/download page

Example | Example
--- | ---
![Screenshot 2024-02-27 at 4 10 07 PM](https://github.com/brave/qa-resources/assets/28145373/fd885c6d-664c-4951-b8e4-2cddb5b08db7) | ![Screenshot 2024-02-27 at 4 11 04 PM](https://github.com/brave/qa-resources/assets/28145373/1e2aca00-62a8-462e-91d4-61e38f075659)

</details>

**Comment by kjozwiak** [comment]
### `macOS x64`

## Downloading using `Chrome` - **PASSED**

* visited `https://bravesoftware.com` using `Chrome 122.0.6261.69 (Official Build) (x86_64)`
* clicked on `Download Brave` that's in the middle of the page and ensured that a `universal dmg` was being downloaded
  * ensured that both `Download Brave` buttons were working correctly on `https://bravesoftware.com`

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------
![Screenshot 2024-02-27 at 4 20 49 PM](https://github.com/brave/qa-resources/assets/2602313/12c67b3b-f0c6-4b97-a1fd-1c7f3d877284) | ![Screenshot 2024-02-27 at 4 17 50 PM](https://github.com/brave/qa-resources/assets/2602313/f6838172-183a-4860-8cd0-9bfd8dda59de) | ![Screenshot 2024-02-27 at 4 16 38 PM](https://github.com/brave/qa-resources/assets/2602313/e92eee87-1aab-4129-a32a-b88ec2d1ef83)

* once downloaded, ensured that installing `Brave` via `drag & drop` worked as expected and installed `Brave`
* ensured that `1.63.164 Chromium: 122.0.6261.69` was being installed without any issues
* ensured that the version that was installed was a `Universal` build
* ensured that the `BRV002` referral code was being displayed via `brave://local-state`

```
         "promo_code": {
            "metadata": [ "user_controlled", "user_modifiable", "extension_modifiable" ],
            "value": "BRV002"
```

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------
![Screenshot 2024-02-27 at 4 18 22 PM](https://github.com/brave/qa-resources/assets/2602313/b3a7d5e4-34cf-4797-8d06-0c0f0326639f) | ![Screenshot 2024-02-27 at 4 19 04 PM](https://github.com/brave/qa-resources/assets/2602313/6d5e96ef-3ed7-4645-b33e-f21cefe2cbf4) | ![Screenshot 2024-02-27 at 4 26 12 PM](https://github.com/brave/qa-resources/assets/2602313/9c9d514e-006b-44d7-a16f-b6af20ba4cfc)

**Comment by LaurenWags** [comment]
Verification in progress with Win 10 x86 as per the below:

<details>
<summary>Edge - InProgress</summary>

Using Edge (version )
- navigated to bravesoftware.com, entered credentials from 1PW
- clicked on "Download" button on main page
   - confirmed downloaded the .dmg file, not .pkg
   - confirmed no ref code appended to the .dmg file
- installed the .dmg file
   - confirmed able to install without issue
   - confirmed the .dmg installed the "Universal" version
   - confirmed current RC version 1.63.164 was installed
- visited brave://local-state
   - confirmed expected ref code (BRV002) was listed
- closed browser, deleted application, profile, and downloaded file
- spot checked the above for other ways to download:
   - "Download" button in the page header
   - bravesoftware.com/download page

Example | Example | Example
--- | --- | ---

</details>
