### ISSUE TITLE
Feri

### ISSUE THREAD

**Issue by Feri3149** [brave/qa-resources#590]
#### Release Date/Target:

* Release Date:

#### Summary:

Includes the following features/fixes:

*
*

**Milestone:**

**Current Progress:**

* ARM -->
* Tablet -->
* x86 -->

**Manual Passes:**

* ARM -->
* Tablet -->
* x86 -->

**Comment by Feri3149** [comment]
Brave please help me for vpn

**Comment by bsclifton** [comment]
@Feri3149 can you please contact our support? What specific problem do you have?

You should be able to open a ticket in the browser; if not you can contact support via our Community site
https://community.brave.com/c/support-and-troubleshooting/firewall-vpn/137
